import type { NewsFrontmatter } from "@/content/news";
import newsManifest from "../../content/news/manifest.json";

/**
 * The only reader of `content/news/manifest.json` (generated by `npm run content:index`), newest first (D-07-06).
 * Kept apart from `news.ts` so `validate.ts` and the `tsx` check scripts can read it
 * without importing the lectures layer or the MDX registry.
 */
export const newsManifestEntries = [...(newsManifest as NewsFrontmatter[])].sort((a, b) =>
  b.date.localeCompare(a.date),
);

const newsManifestSlugs = new Set(newsManifestEntries.map((entry) => entry.slug));

export function hasNewsSlug(slug: string): boolean {
  return newsManifestSlugs.has(slug);
}
