// AUTO-GENERATED by scripts/generate-publications-index.ts — do not edit manually.
import type { ComponentType } from "react";

import type { PublicationFrontmatter } from "./publications";

import PublicationContent0, { frontmatter as PublicationFrontmatter0 } from "../../content/publications/ikona-dzis.mdx";

type PublicationModule = {
  Content: ComponentType;
  frontmatter: PublicationFrontmatter;
};

export const publicationModules: Record<string, PublicationModule> = {
  "ikona-dzis": { Content: PublicationContent0, frontmatter: PublicationFrontmatter0 as PublicationFrontmatter },
};
