/**
 * Generate article/publication registries for src/content/articles.ts and publications.ts.
 *
 * When to run: after adding, renaming or removing an article or publication MDX file, or editing its frontmatter.
 * Usage: npm run content:index (runs this and generate-news-index.ts)
 * `scripts/check-content.ts` (prebuild) compares the committed files with `buildPublicationsIndex()`.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { validatePublicationSlugCollisions } from "../src/content/publication-slugs";
import type { GeneratedFile } from "./generate-news-index";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ARTICLES_DIR = join(ROOT, "content/articles");
const PUBLICATIONS_DIR = join(ROOT, "content/publications");
const ARTICLES_REGISTRY_PATH = join(ROOT, "src/content/articles-registry.ts");
const PUBLICATIONS_REGISTRY_PATH = join(ROOT, "src/content/publications-registry.ts");

const FRONTMATTER_MARKER = "export const frontmatter = ";

type MdxFileEntry = {
  filename: string;
  slug: string;
};

function readSlugFromMdx(filePath: string): string {
  const source = readFileSync(filePath, "utf8");
  const start = source.indexOf(FRONTMATTER_MARKER);

  if (start === -1) {
    throw new Error(`Missing frontmatter export in ${filePath}`);
  }

  const jsonStart = start + FRONTMATTER_MARKER.length;
  const semicolonIndex = source.indexOf(";", jsonStart);

  if (semicolonIndex === -1) {
    throw new Error(`Malformed frontmatter export in ${filePath}`);
  }

  const frontmatter = JSON.parse(source.slice(jsonStart, semicolonIndex)) as { slug: string };
  return frontmatter.slug;
}

function listMdxFiles(directory: string): MdxFileEntry[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith(".mdx") && !name.endsWith("-body.mdx"))
    .sort((a, b) => a.localeCompare(b))
    .map((filename) => {
      const filePath = join(directory, filename);
      return {
        filename,
        slug: readSlugFromMdx(filePath),
      };
    });
}

function buildRegistry(
  outputPath: string,
  importPrefix: string,
  typeName: string,
  frontmatterType: string,
  files: MdxFileEntry[],
  contentDir: string,
): GeneratedFile {
  const imports = files.map(({ filename }, index) => {
    const moduleName = `${importPrefix}Content${index}`;
    return `import ${moduleName}, { frontmatter as ${importPrefix}Frontmatter${index} } from "../../content/${contentDir}/${filename}";`;
  });

  const registryEntries = files.map(({ slug }, index) => {
    const slugKey = JSON.stringify(slug);
    return `  ${slugKey}: { Content: ${importPrefix}Content${index}, frontmatter: ${importPrefix}Frontmatter${index} as ${frontmatterType} },`;
  });

  const content = [
    "// AUTO-GENERATED by scripts/generate-publications-index.ts — do not edit manually.",
    'import type { ComponentType } from "react";',
    "",
    `import type { ${frontmatterType} } from "./${contentDir === "articles" ? "articles" : "publications"}";`,
    "",
    ...imports,
    "",
    `type ${typeName} = {`,
    "  Content: ComponentType;",
    `  frontmatter: ${frontmatterType};`,
    "};",
    "",
    `export const ${importPrefix.toLowerCase()}Modules: Record<string, ${typeName}> = {`,
    ...registryEntries,
    "};",
    "",
  ].join("\n");

  return { path: outputPath, content };
}

/** Article and publication registries exactly as `generatePublicationsIndex()` writes them. */
export function buildPublicationsIndex(): GeneratedFile[] {
  const articleFiles = listMdxFiles(ARTICLES_DIR);
  const publicationFiles = listMdxFiles(PUBLICATIONS_DIR);

  validatePublicationSlugCollisions(
    publicationFiles.map((file) => file.slug),
    articleFiles.map((file) => file.slug),
  );

  return [
    buildRegistry(
      ARTICLES_REGISTRY_PATH,
      "Article",
      "ArticleModule",
      "ArticleFrontmatter",
      articleFiles,
      "articles",
    ),
    buildRegistry(
      PUBLICATIONS_REGISTRY_PATH,
      "Publication",
      "PublicationModule",
      "PublicationFrontmatter",
      publicationFiles,
      "publications",
    ),
  ];
}

export function generatePublicationsIndex(): { articles: number; publications: number } {
  const files = buildPublicationsIndex();
  files.forEach((file) => writeFileSync(file.path, file.content, "utf8"));

  return {
    articles: listMdxFiles(ARTICLES_DIR).length,
    publications: listMdxFiles(PUBLICATIONS_DIR).length,
  };
}
