/**
 * Generate article/publication registries for src/content/articles.ts and publications.ts.
 *
 * Usage: npx tsx -e "import { generatePublicationsIndex } from './scripts/generate-publications-index.ts'; generatePublicationsIndex();"
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { validatePublicationSlugCollisions } from "../src/content/publication-slugs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ARTICLES_DIR = join(ROOT, "content/articles");
const PUBLICATIONS_DIR = join(ROOT, "content/publications");
const ARTICLES_REGISTRY_PATH = join(ROOT, "src/content/articles-registry.ts");
const PUBLICATIONS_REGISTRY_PATH = join(ROOT, "src/content/publications-registry.ts");

const FRONTMATTER_MARKER = "export const frontmatter = ";

type MdxFileEntry = {
  filename: string;
  slug: string;
};

function readSlugFromMdx(filePath: string): string {
  const source = readFileSync(filePath, "utf8");
  const start = source.indexOf(FRONTMATTER_MARKER);

  if (start === -1) {
    throw new Error(`Missing frontmatter export in ${filePath}`);
  }

  const jsonStart = start + FRONTMATTER_MARKER.length;
  const semicolonIndex = source.indexOf(";", jsonStart);

  if (semicolonIndex === -1) {
    throw new Error(`Malformed frontmatter export in ${filePath}`);
  }

  const frontmatter = JSON.parse(source.slice(jsonStart, semicolonIndex)) as { slug: string };
  return frontmatter.slug;
}

function listMdxFiles(directory: string): MdxFileEntry[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith(".mdx") && !name.endsWith("-body.mdx"))
    .sort((a, b) => a.localeCompare(b))
    .map((filename) => {
      const filePath = join(directory, filename);
      return {
        filename,
        slug: readSlugFromMdx(filePath),
      };
    });
}

function generateRegistry(
  outputPath: string,
  importPrefix: string,
  typeName: string,
  frontmatterType: string,
  files: MdxFileEntry[],
  contentDir: string,
): void {
  const imports = files.map(({ filename }, index) => {
    const moduleName = `${importPrefix}Content${index}`;
    return `import ${moduleName}, { frontmatter as ${importPrefix}Frontmatter${index} } from "../../content/${contentDir}/${filename}";`;
  });

  const registryEntries = files.map(({ slug }, index) => {
    const slugKey = JSON.stringify(slug);
    return `  ${slugKey}: { Content: ${importPrefix}Content${index}, frontmatter: ${importPrefix}Frontmatter${index} as ${frontmatterType} },`;
  });

  const source = [
    "// AUTO-GENERATED by scripts/generate-publications-index.ts — do not edit manually.",
    'import type { ComponentType } from "react";',
    "",
    `import type { ${frontmatterType} } from "./${contentDir === "articles" ? "articles" : "publications"}";`,
    "",
    ...imports,
    "",
    `type ${typeName} = {`,
    "  Content: ComponentType;",
    `  frontmatter: ${frontmatterType};`,
    "};",
    "",
    `export const ${importPrefix.toLowerCase()}Modules: Record<string, ${typeName}> = {`,
    ...registryEntries,
    "};",
    "",
  ].join("\n");

  writeFileSync(outputPath, source, "utf8");
}

export function generatePublicationsIndex(): { articles: number; publications: number } {
  const articleFiles = listMdxFiles(ARTICLES_DIR);
  const publicationFiles = listMdxFiles(PUBLICATIONS_DIR);

  validatePublicationSlugCollisions(
    publicationFiles.map((file) => file.slug),
    articleFiles.map((file) => file.slug),
  );

  generateRegistry(
    ARTICLES_REGISTRY_PATH,
    "Article",
    "ArticleModule",
    "ArticleFrontmatter",
    articleFiles,
    "articles",
  );

  generateRegistry(
    PUBLICATIONS_REGISTRY_PATH,
    "Publication",
    "PublicationModule",
    "PublicationFrontmatter",
    publicationFiles,
    "publications",
  );

  return { articles: articleFiles.length, publications: publicationFiles.length };
}
