/**
 * Generate content/news/manifest.json for src/content/news.ts.
 *
 * Next.js/Turbopack does not resolve import.meta.glob for content/news/*.mdx.
 * The list page reads frontmatter from the manifest; article pages import MDX individually.
 *
 * Usage: npx tsx -e "import { generateNewsManifest } from './scripts/generate-news-index.ts'; generateNewsManifest();"
 * Also invoked at the end of scripts/generate-news-sample.ts.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const NEWS_DIR = join(ROOT, "content/news");
const OUTPUT_PATH = join(ROOT, "content/news/manifest.json");
const REGISTRY_PATH = join(ROOT, "src/content/news-registry.ts");

const FRONTMATTER_MARKER = "export const frontmatter = ";

export type NewsManifestEntry = {
  slug: string;
  title: string;
  date: string;
  dateEnd?: string;
  kind: string;
  excerpt?: string;
  venue?: string;
  sample?: boolean;
  featured?: boolean;
  bodyText?: string;
  cover?: {
    src: string;
    alt: string;
    width: number;
    height: number;
    caption?: string;
  };
  images?: Array<{
    src: string;
    alt: string;
    width: number;
    height: number;
    caption?: string;
  }>;
  poster?: {
    src: string;
    alt: string;
    width: number;
    height: number;
    caption?: string;
  };
};

function readFrontmatterFromMdx(filePath: string): NewsManifestEntry {
  const source = readFileSync(filePath, "utf8");
  const start = source.indexOf(FRONTMATTER_MARKER);

  if (start === -1) {
    throw new Error(`Missing frontmatter export in ${filePath}`);
  }

  const jsonStart = start + FRONTMATTER_MARKER.length;
  const lineEnd = source.indexOf(";\r\n", jsonStart);
  const jsonEnd = lineEnd !== -1 ? lineEnd : source.indexOf(";\n", jsonStart);

  if (jsonEnd === -1) {
    throw new Error(`Malformed frontmatter export in ${filePath}`);
  }

  return JSON.parse(source.slice(jsonStart, jsonEnd)) as NewsManifestEntry;
}

function extractBodyText(source: string): string {
  const start = source.indexOf(FRONTMATTER_MARKER);
  if (start === -1) {
    return "";
  }

  const jsonStart = start + FRONTMATTER_MARKER.length;
  const lineEnd = source.indexOf(";\r\n", jsonStart);
  const jsonEnd = lineEnd !== -1 ? lineEnd : source.indexOf(";\n", jsonStart);
  if (jsonEnd === -1) {
    return "";
  }

  const bodyStart = lineEnd !== -1 ? jsonEnd + 3 : jsonEnd + 2;

  return source
    .slice(bodyStart)
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function validateFeaturedEntries(entries: NewsManifestEntry[]): void {
  const featuredEntries = entries.filter((entry) => entry.featured);

  if (featuredEntries.length > 1) {
    const slugs = featuredEntries.map((entry) => entry.slug).join(", ");
    throw new Error(`At most one news entry may have featured: true (found: ${slugs})`);
  }

  const featured = featuredEntries[0];
  if (featured && !featured.cover) {
    throw new Error(`Featured news entry "${featured.slug}" must have a cover image`);
  }
}

type MdxFileEntry = {
  filename: string;
  frontmatter: NewsManifestEntry;
};

function generateNewsRegistry(files: MdxFileEntry[]): void {
  const imports = files.map(({ filename }, index) => {
    const moduleName = `NewsContent${index}`;
    return `import ${moduleName}, { frontmatter as frontmatter${index} } from "../../content/news/${filename}";`;
  });

  const registryEntries = files.map(({ frontmatter }, index) => {
    const slug = JSON.stringify(frontmatter.slug);
    return `  ${slug}: { Content: NewsContent${index}, frontmatter: frontmatter${index} as NewsFrontmatter },`;
  });

  const source = [
    "// AUTO-GENERATED by scripts/generate-news-index.ts — do not edit manually.",
    'import type { ComponentType } from "react";',
    "",
    'import type { NewsFrontmatter } from "./news";',
    "",
    ...imports,
    "",
    "type NewsModule = {",
    "  Content: ComponentType;",
    "  frontmatter: NewsFrontmatter;",
    "};",
    "",
    "export const newsModules: Record<string, NewsModule> = {",
    ...registryEntries,
    "};",
    "",
  ].join("\n");

  writeFileSync(REGISTRY_PATH, source, "utf8");
}

export function generateNewsManifest(): number {
  const filenames = readdirSync(NEWS_DIR)
    .filter((name) => name.endsWith(".mdx"))
    .sort((a, b) => a.localeCompare(b));

  const files = filenames.map((filename) => {
    const filePath = join(NEWS_DIR, filename);
    const source = readFileSync(filePath, "utf8");
    const frontmatter = readFrontmatterFromMdx(filePath);
    const bodyText = extractBodyText(source);

    return {
      filename,
      frontmatter: {
        ...frontmatter,
        ...(bodyText ? { bodyText } : {}),
      },
    };
  });

  const entries = files.map(({ frontmatter }) => frontmatter);
  validateFeaturedEntries(entries);

  writeFileSync(OUTPUT_PATH, `${JSON.stringify(entries, null, 2)}\n`, "utf8");
  generateNewsRegistry(files);
  return entries.length;
}
